### ISSUE TITLE
rustc version from rust-toolchain is only respected within nix-shell

### ISSUE THREAD

**Issue by rkrzr** [fatho/template-rust-nix#1]
Hi Fabian,

Thanks for creating this nice template :)

I just noticed that when I update the rustc version in `rust-toolchain` to `1.69.0` then this change will only be reflected within a `nix-shell`, but not by `direnv` in the automatic Nix environment when you enter the directory. That shell will still use `1.63.0` then (also provided by Nix).

Would I need to update `sources.json` to a newer nixpkgs revision to get a newer `rustc` version in the direnv shell?

**Comment by fatho** [comment]
That happens because direnv doesn't know by default that `rust-toolchain` influences the outcome of the nix evaluation, so after changing that a manual `direnv reload` was needed.

I fixed this in https://github.com/fatho/template-rust-nix/commit/33d54a399af582a55930ece49148b62061457b41 by making it watch the imported files as well. That way, it should now automatically reload the shell environment when `rust-toolchain` is bumped.
